# ----------------------------------------------------- 
# General
# ----------------------------------------------------- 
general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
    col.active_border = rgba(88c0d0ff)
    col.inactive_border=0xff434c5e

    layout = dwindle

    allow_tearing = false
}

decoration {
    rounding = 15
    
    blur {
        enabled = true
        size = 6
        passes = 3
	      new_optimizations = true
  	    ignore_opacity = true
	      xray = false
    }

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

blurls=waybar

dwindle {
    pseudotile = yes 
    preserve_split = yes
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = off
}

misc {
    animate_manual_resizes = true
}

