# ----------------------------------------------------- 
# Hyprlock
# ----------------------------------------------------- 
background {
    monitor =
    path = /home/gurami/Pictures/wallpapers/Forest.png   # only png supported for now

    blur_passes = 4 # 0 disables blurring
    blur_size = 6
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.1 
    dots_spacing = 0.3 
    outer_color = rgba(46, 52, 64, 1)
    inner_color = rgba(94, 129, 172, 1)
    font_color = rgba(59, 66, 82, 1)
    fade_on_empty = false
    placeholder_text = 

    position = 0, 0
    halign = center
    valign = center
}

label {
  monitor =
  text = $TIME
  color = rgba(200, 200, 200, 1.0)
  font_size = 45
  font_family = FiraCode Medium

  position = 0, 230
  halign = center
  valign = center
}

label {
    monitor =
    text = Hi, 
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = FiraCode Medium

    position = -85, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER:)
    color = rgba(129, 161, 193, 1)
    font_size = 25
    font_family = FiraCode Medium

    position = 35, 80
    halign = center
    valign = center
}
