# ----------------------------------------------------- 
# Hypridle
# ----------------------------------------------------- 
listener {
    timeout = 300 # 3mins
    on-timeout = pidof hyprlock || hyprlock
}
