#  _   _                  _                 _  
# | | | |_   _ _ __  _ __| | __ _ _ __   __| | 
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` | 
# |  _  | |_| | |_) | |  | | (_| | | | | (_| | 
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| 
#        |___/|_|                              
#  
# ----------------------------------------------------- 

# -----------------------------------------------------
# Variables
# ----------------------------------------------------- 
$terminal = alacritty
$fileManager = nautilus
$menu = rofi -show drun
$editor = code --disable-gpu
$browser = vivaldi
$logout = wlogout --protocol layer-shell -b 6 -T
$NotificationCenter = swaync-client -t -sw
$wallpaper = ~/.config/hypr/scripts/WallpaperRandom.sh
$screenshot = grim -g "$(slurp -d)" - | wl-copy

# -----------------------------------------------------
# Monitors
# ----------------------------------------------------- 
source = ~/.config/hypr/monitors.conf

# -----------------------------------------------------
# Startup
# -----------------------------------------------------
source = ~/.config/hypr/autostart.conf

# ----------------------------------------------------- 
# Environment
# ----------------------------------------------------- 
source = ~/.config/hypr/environment.conf

# -----------------------------------------------------
# Inputs
# ----------------------------------------------------- 
source = ~/.config/hypr/inputs.conf

# ----------------------------------------------------- 
# General
# ----------------------------------------------------- 
source = ~/.config/hypr/general.conf

# ----------------------------------------------------- 
# Animations
# ----------------------------------------------------- 
source = ~/.config/hypr/animations.conf

# ----------------------------------------------------- 
# Keybindings
# -----------------------------------------------------
source = ~/.config/hypr/keybindings.conf

# ----------------------------------------------------- 
# Window Rules
# ----------------------------------------------------- 
source = ~/.config/hypr/windowrules.conf
