# ----------------------------------------------------- 
# Inputs
# ----------------------------------------------------- 
input {
    kb_layout = us,ge
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
    force_no_accel = 1
}
