site_name: Gurjaka's Dotfiles
site_description: My minimal, suckless, Wayland-first dotfiles and setup configs
site_author: Gurami Esartia
repo_url: https://github.com/Gurjaka/Dotfiles

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: cyan
  font:
    text: Roboto
    code: Fira Code
  logo: assets/nix-snowflake.svg
  favicon: assets/nix-snowflake.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - navigation.sections
    - navigation.expand
    - navigation.footer

extra:
  generator: false

extra_css:
  - stylesheets/nord.css

plugins:
  - search

nav:
  - Home: index.md
  - Philosophy: philosophy.md
  - Qtile: qtile.md
  - Neovim: neovim.md
  - Terminal: terminal.md
  - Nix: nix.md
  - Wallpapers: wallpaper.md
  - KB-Layout: kb-layout.md
  - Usage: usage.md
  - Installation: installation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
