-- Core
require('core.options')
require('core.autocmds')
require('core.keymaps')
require('core.theme_auto')

-- Plugins
require('plugins.alpha')
require('plugins.bufferline')
require('plugins.cmp')
require('plugins.conform')
require('plugins.illuminate')
require('plugins.indent-blankline')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.mini-clue')
require('plugins.mini-pairs')
require('plugins.mini-surround')
require('plugins.noice')
require('plugins.notify')
require('plugins.nvim-tree')
require('plugins.render-markdown')
require('plugins.telescope')
require('plugins.todo-comments')
require('plugins.treesitter')
require('plugins.web-devicons')
require('plugins.yazi-nvim')
