-- Core
require('core.options')
require('core.autocmds')
require('core.keymaps')

-- Plugins
require('plugins.alpha')
require('plugins.cmp')
require('plugins.conform')
require('plugins.indent-blankline')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.noice')
require('plugins.notify')
require('plugins.nvim-surround')
require('plugins.yazi-nvim')
require('plugins.render-markdown')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.web-devicons')
