# ----------------------------------------------------- 
# Startup Apps
# ----------------------------------------------------- 
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = hypridle &
exec-once = swaync &
exec-once = waybar &
exec-once = $wallpaper
exec-once = udiskie &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = nm-applet --indicator
